# ChopTree 5
# ReWritten by gkid117 and Updated by EpiCanard
# 
# Configuration File
# 
# ActiveByDefault: Do new players given choptree.chop 'POP' trees by default?
# 
# UseAnything: Can a player use anything to 'POP' trees (rather than just an axe)?
# 
# AllowedTools: If UseAnything is false, what tools can be used (separated with commas, NO SPACES)?
# 
# MoreDamageToTools: Do tools take the amount of damage they WOULD if they chopped the whole tree?
# 
# InterruptIfToolBreaks: If the tool does not have enough durability to 'POP' the whole tree, should the 'POP' be stopped?
# 
# LogsMoveDown: Are all item drops dropped by the chopped log (rather than by each 'POP'ed log)?
# 
# OnlyTrees: Does the 'POP' only work if the player chopped a tree (rather than ANY pile of logs)?
# 
# PopLeaves: Leaves are 'POP'ed when teh tree 'POP's
# 
# LeafRadius: How far out should leaves be popped from each log block

ActiveByDefault: true
UseAnything: false
AllowedTools:
  - GOLDEN_AXE
MoreDamgeToTools: false
InterruptIfToolBreaks: false
LogsMoveDown: false
OnlyTrees: true
PopLeaves: false
LeafRadius: 3
AllowedWoodBlocks: 
  - ACACIA_LOG
  - BIRCH_LOG
  - DARK_OAK_LOG
  - JUNGLE_LOG
  - OAK_LOG
  - SPRUCE_LOG
  - CRIMSON_STEM
  - WARPED_STEM
LeavesForDecay:
  - ACACIA_LEAVES
  - BIRCH_LEAVES
  - DARK_OAK_LEAVES
  - JUNGLE_LEAVES
  - OAK_LEAVES
  - SPRUCE_LEAVES
  - NETHER_WART_BLOCK
  - WARPED_WART_BLOCK
